#!/usr/bin/env python

import sys

from optparse import OptionParser

from slingrpm.tasks import update_repo

parser = OptionParser()
parser.add_option('-r', '--repo_dir',
                  help="repostiory to update",
                  default=None, action="store", type="string",
                  dest="repo_dir")

(options, args) = parser.parse_args()

_errors = []

if not options.repo_dir:
    _errors.append('REPO_DIR required')

if len(_errors) > 0:
    for error in _errors:
        print error
    parser.print_help()
    sys.exit(1)

update_repo(options.repo_dir)
